/**:
  ros__parameters:
    log_interval_sec: 5.0

    model:
      path: ""
      device: "cpu"

    lidar:
      angle_min: -1.5666074752807617
      angle_max: 1.5707963705062866
      range_min: 0.0
      range_max: 25.0

    pointcloud:
      topic: "/sensing/lidar/pointcloud"
      z_min: -1.0
      z_max: 1.0

    odometry:
      topic: "/localization/kinematic_state"

    control:
      topic: "/control/command/control_cmd"
      dt: 0.05

    vehicle:
      min_speed_mps: 0.0
      max_speed_mps: 4.165
      max_accel_mps2: 3.0
      max_brake_mps2: 5.0
      max_steer_rad: 0.75

    debug: false
